/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutCompleteOrderIdRouteImport } from './routes/checkout/complete/$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCompleteOrderIdRoute = CheckoutCompleteOrderIdRouteImport.update({
  id: '/checkout/complete/$orderId',
  path: '/checkout/complete/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/stats': typeof StatsRoute
  '/wishlist': typeof WishlistRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/complete/$orderId': typeof CheckoutCompleteOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/stats': typeof StatsRoute
  '/wishlist': typeof WishlistRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/checkout/complete/$orderId': typeof CheckoutCompleteOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/stats': typeof StatsRoute
  '/wishlist': typeof WishlistRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/complete/$orderId': typeof CheckoutCompleteOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/register'
    | '/stats'
    | '/wishlist'
    | '/books/$bookId'
    | '/checkout/'
    | '/checkout/complete/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/register'
    | '/stats'
    | '/wishlist'
    | '/books/$bookId'
    | '/checkout'
    | '/checkout/complete/$orderId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/register'
    | '/stats'
    | '/wishlist'
    | '/books/$bookId'
    | '/checkout/'
    | '/checkout/complete/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  StatsRoute: typeof StatsRoute
  WishlistRoute: typeof WishlistRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutCompleteOrderIdRoute: typeof CheckoutCompleteOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/complete/$orderId': {
      id: '/checkout/complete/$orderId'
      path: '/checkout/complete/$orderId'
      fullPath: '/checkout/complete/$orderId'
      preLoaderRoute: typeof CheckoutCompleteOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  StatsRoute: StatsRoute,
  WishlistRoute: WishlistRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutCompleteOrderIdRoute: CheckoutCompleteOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
